name: nativeflow_payment_sdk_wrapper
description: Example payment SDK wrapper built with NativeFlow Bridge.
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  nativeflow_bridge_annotations:
    path: ../../packages/bridge_annotations
  nativeflow_bridge_core:
    path: ../../packages/bridge_core
  nativeflow_bridge_runtime:
    path: ../../packages/bridge_runtime

dev_dependencies:
  build_runner: ^2.4.15
  nativeflow_bridge_generator:
    path: ../../packages/bridge_generator
